# Generated by Django 4.2.6 on 2023-11-15 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CloudProvider',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CloudProviderRegion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('cloud_provider_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.cloudprovider')),
            ],
        ),
        migrations.CreateModel(
            name='CloudResourceType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CloudStageType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CloudProviderSubscription',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('subscription', models.CharField(max_length=200)),
                ('cloud_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.cloudprovider')),
            ],
        ),
        migrations.CreateModel(
            name='CloudProviderStage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('cloud_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.cloudprovider')),
                ('cloud_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.cloudproviderregion')),
                ('cloud_subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.cloudprovidersubscription')),
                ('stage_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.cloudstagetype')),
            ],
        ),
    ]
