# Generated by Django 4.2.6 on 2023-11-15 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_awsbucket'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CloudStageType',
            new_name='CloudStage',
        ),
        migrations.RemoveField(
            model_name='cloudproviderstage',
            name='cloud_provider',
        ),
        migrations.RemoveField(
            model_name='cloudproviderstage',
            name='cloud_region',
        ),
        migrations.RemoveField(
            model_name='cloudproviderstage',
            name='cloud_subscription',
        ),
        migrations.RemoveField(
            model_name='cloudproviderstage',
            name='stage_type',
        ),
        migrations.DeleteModel(
            name='AWSBucket',
        ),
        migrations.DeleteModel(
            name='CloudProviderStage',
        ),
    ]
