# Generated by Django 4.2.6 on 2023-11-15 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_rename_cloudstagetype_cloudstage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudprovidersubscription',
            name='stage',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='portal.cloudstage'),
        ),
    ]
