# Generated by Django 4.2.6 on 2023-11-15 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_awsbucket'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AWSBucket',
        ),
    ]
