# Generated by Django 4.2.6 on 2023-11-15 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_cloudresource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloudresource',
            name='acl',
            field=models.CharField(blank=True, editable=False, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cloudresource',
            name='compartment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.cloudresource'),
        ),
        migrations.AlterField(
            model_name='cloudresource',
            name='encryption',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cloudresource',
            name='lifecycle',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cloudresource',
            name='logging',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cloudresource',
            name='notification',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cloudresource',
            name='policy',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cloudresource',
            name='private_endpoint',
            field=models.CharField(blank=True, editable=False, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cloudresource',
            name='public_endpoint',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cloudresource',
            name='resource_id',
            field=models.CharField(blank=True, editable=False, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cloudresource',
            name='versioning',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
