apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariapv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /data/mariapv/
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariapvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: jujuba
  name: mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - name: mariadb
        image: mariadb
        ports:
        - containerPort: 3306 
        env:
        - name: MARIADB_ALLOW_EMPTY_ROOT_PASSWORD
          value: "0"
        - name: MARIADB_ROOT_PASSWORD
          value: jujuba
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: dbdata
        resources:
          limits:
            memory: 512Mi
            cpu: 500m
          requests:
            memory: 256Mi
            cpu: 200m
      volumes:
      - name: dbdata
        persistentVolumeClaim:
          claimName: mariapvc
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mariadb
  name: mariadb-service
spec:
  ports:
  - name: "3306"
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: mariadb
    name: mariadb
  type: ClusterIP